# Dockerfile.dev.cra
FROM node:20-alpine

# تنظیم پوشه کاری داخل کانتینر
WORKDIR /app

# کپی فایل‌های package.json و package-lock.json
COPY package*.json ./

# نصب وابستگی‌ها
RUN npm install

# کپی بقیه پروژه
COPY . .

# پورت پیش‌فرض CRA
EXPOSE 3000

# فرمان اجرای dev server
CMD ["npm", "start"]
