networks:
  appnet:

volumes:
  iam-db:
  portfolio-db:
  request-db:
  redis-data:
  wwwroot-data:

services:

  gateway:
    build:
      context: ./  # Root directory
      dockerfile: ./src/gateway/Gateway/Dockerfile
    container_name: gateway
    depends_on:
      - iam-api
      - portfolio-api
      - request-api
    networks:
      - appnet
    ports:
      - "5157:5157"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5157"]
      interval: 30s
      retries: 3
      start_period: 20s

  iam-api:
    build:
      context: ./  # Root directory
      dockerfile: ./src/services/iam/IAM.Api/Dockerfile
    container_name: iam-api
    environment:
      - ConnectionStrings__Default=Host=iam-db;Database=iam;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      iam-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 3
      start_period: 20s

  iam-db:
    image: postgres:16
    container_name: iam-db
    environment:
      POSTGRES_DB: iam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - iam-db:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      retries: 3
      start_period: 20s

  portfolio-api:
    build:
      context: ./  # Root directory
      dockerfile: ./src/services/portfolio/PortFolioService.Api/Dockerfile
    container_name: portfolio-api
    environment:
      - ConnectionStrings__Default=Host=portfolio-db;Database=portfolio;Username=postgres;Password=postgres
    depends_on:
      portfolio-db:
        condition: service_healthy
    networks:
      - appnet
    volumes:
      - wwwroot-data:/Backend/src/services/portfolio/PortFolioService.Api/wwwroot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 3
      start_period: 20s

  portfolio-db:
    image: postgres:16
    container_name: portfolio-db
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - portfolio-db:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      retries: 3
      start_period: 20s

  request-api:
    build:
      context: ./  # Root directory
      dockerfile: ./src/services/request/Request.Api/Dockerfile
    container_name: request-api
    environment:
      - ConnectionStrings__Default=Host=request-db;Database=request;Username=postgres;Password=postgres
    depends_on:
      request-db:
        condition: service_healthy
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 3
      start_period: 20s

  request-db:
    image: postgres:16
    container_name: request-db
    environment:
      POSTGRES_DB: request
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - request-db:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      retries: 3
      start_period: 20s

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - appnet
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - appnet
    ports:
      - "3000:80"
    depends_on:
      - gateway
    environment:
      - VITE_API_URL=http://gateway:5157
